name: CD

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normalize owner to lowercase
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./services/ai-learning-coach-api
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/ai-learning-coach-api:latest
            ghcr.io/${{ env.OWNER_LC }}/ai-learning-coach-api:${{ github.sha }}

      # - name: Build & Push Worker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./services/ai-worker
      #     push: true
      #     tags: |
      #       ghcr.io/${{ env.OWNER_LC }}/ai-learning-coach-worker:latest
      #       ghcr.io/${{ env.OWNER_LC }}/ai-learning-coach-worker:${{ github.sha }}
